SET TIMING ON
SET SERVEROUTPUT ON

-- PROCEDURE 실행
EXEC DEV.GENERATE_ORD_BASE(15000000, 10000);

DROP TABLE DEV.ORD_TEMP2 PURGE;
CREATE TABLE DEV.ORD_TEMP2 AS
SELECT
        ROWNUM ORD_NO
      , ORD_DT
      , ORD_HMS
      , SHOP_NO, UPPER2, UPPER_CASE, LOWER_CASE, ALPHABET, ALPHABET_NUMERIC
FROM    (
            SELECT  ORD_DT, ORD_HMS, SHOP_NO, UPPER2, UPPER_CASE, LOWER_CASE, ALPHABET, ALPHABET_NUMERIC
            FROM    DEV.ORD_TEMP
            ORDER BY ORD_DT, ORD_HMS
        )
;


INSERT  /*+ APPEND */
        INTO DEV.ORD (ORD_NO, ORD_DT, ORD_HMS, SHOP_NO, UPPER2, UPPER_CASE, LOWER_CASE, ALPHABET, ALPHABET_NUMERIC)
SELECT  ORD_NO, ORD_DT, ORD_HMS, SHOP_NO, UPPER2, UPPER_CASE, LOWER_CASE, ALPHABET, NULL
FROM    DEV.ORD_TEMP2
;

COMMIT;


ALTER TABLE DEV.ORD ADD CONSTRAINT ORD_PK PRIMARY KEY (ORD_NO);

EXEC DEV.INSERT_ORD_ITEM(15000000, 10000);

CREATE INDEX DEV.ORD_X01 ON DEV.ORD(ORD_DT, ORD_HMS);

ALTER TABLE DEV.ORD_ITEM ADD CONSTRAINT ORD_ITEM_PK PRIMARY KEY (ORD_NO, ITEM_ID);

CREATE INDEX DEV.ORD_ITEM_X01 ON DEV.ORD_ITEM(ORD_DT, ORD_HMS);
