COMMENT ON TABLE DEV.ORD_LIST  IS '주문';
    COMMENT ON COLUMN DEV.ORD_LIST.ORD_NO IS '주문번호' ;
    COMMENT ON COLUMN DEV.ORD_LIST.ORD_YM IS '주문년월' ;
    COMMENT ON COLUMN DEV.ORD_LIST.ORD_DT IS '주문일자' ;
    COMMENT ON COLUMN DEV.ORD_LIST.ORD_HMS IS '주문시간' ;
    COMMENT ON COLUMN DEV.ORD_LIST.SHOP_NO IS '매장번호' ;
    COMMENT ON COLUMN DEV.ORD_LIST.UPPER2 IS '대문자2자리' ;
    COMMENT ON COLUMN DEV.ORD_LIST.UPPER_CASE IS '대문자10자리' ;
    COMMENT ON COLUMN DEV.ORD_LIST.LOWER_CASE IS '소문자10자리' ;
    COMMENT ON COLUMN DEV.ORD_LIST.ALPHABET IS '대소문자' ;
    COMMENT ON COLUMN DEV.ORD_LIST.ALPHABET_NUMERIC IS '대소문자숫자' ;

COMMENT ON TABLE DEV.ORD_RANGE  IS '주문';
    COMMENT ON COLUMN DEV.ORD_RANGE.ORD_NO IS '주문번호' ;
    COMMENT ON COLUMN DEV.ORD_RANGE.ORD_YM IS '주문년월' ;
    COMMENT ON COLUMN DEV.ORD_RANGE.ORD_DT IS '주문일자' ;
    COMMENT ON COLUMN DEV.ORD_RANGE.ORD_HMS IS '주문시간' ;
    COMMENT ON COLUMN DEV.ORD_RANGE.SHOP_NO IS '매장번호' ;
    COMMENT ON COLUMN DEV.ORD_RANGE.UPPER2 IS '대문자2자리' ;
    COMMENT ON COLUMN DEV.ORD_RANGE.UPPER_CASE IS '대문자10자리' ;
    COMMENT ON COLUMN DEV.ORD_RANGE.LOWER_CASE IS '소문자10자리' ;
    COMMENT ON COLUMN DEV.ORD_RANGE.ALPHABET IS '대소문자' ;
    COMMENT ON COLUMN DEV.ORD_RANGE.ALPHABET_NUMERIC IS '대소문자숫자' ;

COMMENT ON TABLE DEV.ORD_ITEM_LIST  IS '주문상품';
    COMMENT ON COLUMN DEV.ORD_ITEM_LIST.ORD_NO IS '주문번호' ;
    COMMENT ON COLUMN DEV.ORD_ITEM_LIST.ITEM_ID IS '상품번호' ;
    COMMENT ON COLUMN DEV.ORD_ITEM_LIST.ORD_ITEM_QTY IS '주문상품수량' ;
    COMMENT ON COLUMN DEV.ORD_ITEM_LIST.ORD_YM IS '주문년월' ;
    COMMENT ON COLUMN DEV.ORD_ITEM_LIST.ORD_DT IS '주문일자' ;
    COMMENT ON COLUMN DEV.ORD_ITEM_LIST.ORD_HMS IS '주문시간' ;
    COMMENT ON COLUMN DEV.ORD_ITEM_LIST.UPPER2 IS '대문자2자리' ;
    COMMENT ON COLUMN DEV.ORD_ITEM_LIST.UPPER_CASE IS '대문자10자리' ;
    COMMENT ON COLUMN DEV.ORD_ITEM_LIST.LOWER_CASE IS '소문자10자리' ;
    COMMENT ON COLUMN DEV.ORD_ITEM_LIST.ALPHABET IS '대소문자' ;
    COMMENT ON COLUMN DEV.ORD_ITEM_LIST.ALPHABET_NUMERIC IS '대소문자숫자' ;

COMMENT ON TABLE DEV.ORD_ITEM_RANGE  IS '주문상품';
    COMMENT ON COLUMN DEV.ORD_ITEM_RANGE.ORD_NO IS '주문번호' ;
    COMMENT ON COLUMN DEV.ORD_ITEM_RANGE.ITEM_ID IS '상품번호' ;
    COMMENT ON COLUMN DEV.ORD_ITEM_RANGE.ORD_ITEM_QTY IS '주문상품수량' ;
    COMMENT ON COLUMN DEV.ORD_ITEM_RANGE.ORD_YM IS '주문년월' ;
    COMMENT ON COLUMN DEV.ORD_ITEM_RANGE.ORD_DT IS '주문일자' ;
    COMMENT ON COLUMN DEV.ORD_ITEM_RANGE.ORD_HMS IS '주문시간' ;
    COMMENT ON COLUMN DEV.ORD_ITEM_RANGE.UPPER2 IS '대문자2자리' ;
    COMMENT ON COLUMN DEV.ORD_ITEM_RANGE.UPPER_CASE IS '대문자10자리' ;
    COMMENT ON COLUMN DEV.ORD_ITEM_RANGE.LOWER_CASE IS '소문자10자리' ;
    COMMENT ON COLUMN DEV.ORD_ITEM_RANGE.ALPHABET IS '대소문자' ;
    COMMENT ON COLUMN DEV.ORD_ITEM_RANGE.ALPHABET_NUMERIC IS '대소문자숫자' ;


