COMMENT ON TABLE DEV.ORD_LIST_HASH  IS '주문';
    COMMENT ON COLUMN DEV.ORD_LIST_HASH.ORD_NO IS '주문번호' ;
    COMMENT ON COLUMN DEV.ORD_LIST_HASH.ORD_YM IS '주문년월' ;
    COMMENT ON COLUMN DEV.ORD_LIST_HASH.ORD_DT IS '주문일자' ;
    COMMENT ON COLUMN DEV.ORD_LIST_HASH.ORD_HMS IS '주문시간' ;
    COMMENT ON COLUMN DEV.ORD_LIST_HASH.SHOP_NO IS '매장번호' ;
    COMMENT ON COLUMN DEV.ORD_LIST_HASH.UPPER2 IS '대문자2자리' ;
    COMMENT ON COLUMN DEV.ORD_LIST_HASH.UPPER_CASE IS '대문자10자리' ;
    COMMENT ON COLUMN DEV.ORD_LIST_HASH.LOWER_CASE IS '소문자10자리' ;
    COMMENT ON COLUMN DEV.ORD_LIST_HASH.ALPHABET IS '대소문자' ;
    COMMENT ON COLUMN DEV.ORD_LIST_HASH.ALPHABET_NUMERIC IS '대소문자숫자' ;

COMMENT ON TABLE DEV.ORD_ITEM_LIST_HASH  IS '주문상품';
    COMMENT ON COLUMN DEV.ORD_ITEM_LIST_HASH.ORD_NO IS '주문번호' ;
    COMMENT ON COLUMN DEV.ORD_ITEM_LIST_HASH.ITEM_ID IS '상품번호' ;
    COMMENT ON COLUMN DEV.ORD_ITEM_LIST_HASH.ORD_ITEM_QTY IS '주문상품수량' ;
    COMMENT ON COLUMN DEV.ORD_ITEM_LIST_HASH.ORD_YM IS '주문년월' ;
    COMMENT ON COLUMN DEV.ORD_ITEM_LIST_HASH.ORD_DT IS '주문일자' ;
    COMMENT ON COLUMN DEV.ORD_ITEM_LIST_HASH.ORD_HMS IS '주문시간' ;
    COMMENT ON COLUMN DEV.ORD_ITEM_LIST_HASH.UPPER2 IS '대문자2자리' ;
    COMMENT ON COLUMN DEV.ORD_ITEM_LIST_HASH.UPPER_CASE IS '대문자10자리' ;
    COMMENT ON COLUMN DEV.ORD_ITEM_LIST_HASH.LOWER_CASE IS '소문자10자리' ;
    COMMENT ON COLUMN DEV.ORD_ITEM_LIST_HASH.ALPHABET IS '대소문자' ;
    COMMENT ON COLUMN DEV.ORD_ITEM_LIST_HASH.ALPHABET_NUMERIC IS '대소문자숫자' ;

